communication:
  operator_name: test_user
  viz_type: sim_web_visualizer
  viz_host: localhost
  viz_port: 6000
  viz_urdf_paths:
    - assembly/kinova3_robotiq_2f_85/kinova_gen3_robotiq_2f_85_left.urdf
    - assembly/kinova3_robotiq_2f_85/kinova_gen3_robotiq_2f_85_right.urdf
