communication:
  operator_name: test_user
  viz_type: sim_web_visualizer
  viz_host: localhost
  viz_port: 6000
  viz_urdf_paths:
    - assembly/kinova_gen3_lite_gen3_2f/kinova_gen3_lite_gen3_lite_2f_right.urdf
