left:
  retargeting:
    type: vector
    
    # Point to your Robotiq gripper URDF
    urdf_path: hands/2f_85/robotiq_2f_85.urdf
    
    # Wrist link name in Kinova Gen3 
    wrist_link_name: "robotiq_85_base_link"
    
    # For Robotiq, we just need one control point for opening/closing
    target_joint_names: ["robotiq_85_left_knuckle_joint"]
    target_origin_link_names: ["robotiq_85_base_link","robotiq_85_base_link"]
    target_task_link_names: ["robotiq_85_left_finger_tip_link", "robotiq_85_right_finger_tip_link"]
    scaling_factor: 0.8
    
    # You'll need to simplify the hand retargeting for a two-finger gripper
    # This maps human hand opening/closing to gripper
    target_link_human_indices: [[0,0], [4,8]] # Using index finger position to control gripper
    
    # May need tuning for your specific setup
    low_pass_alpha: 0.4
    
  control:
    type: pinocchio
    
    robot_name: kinova_gen3_robotiq_left
    
    # Path to your Kinova config file
    robot_config_path: kinova3_2f_85_left.yml
    
    low_pass_alpha: 0.05
    
    disable_orientation_control: False
    
    # Start with conservative scaling until familiar with system
    motion_scaling_factor: 0.8

right:
  retargeting:
    type: vector
    
    # Point to your Robotiq gripper URDF
    urdf_path: hands/2f_85/robotiq_2f_85.urdf
    
    # Wrist link name in Kinova Gen3 
    wrist_link_name: "robotiq_85_base_link"
    
    # For Robotiq, we just need one control point for opening/closing
    target_joint_names: ["robotiq_85_left_knuckle_joint"]
    target_origin_link_names: ["robotiq_85_base_link","robotiq_85_base_link"]
    target_task_link_names: ["robotiq_85_left_finger_tip_link", "robotiq_85_right_finger_tip_link"]
    scaling_factor: 0.8
    
    # You'll need to simplify the hand retargeting for a two-finger gripper
    # This maps human hand opening/closing to gripper
    target_link_human_indices: [[0,0], [4,8]] # Using index finger position to control gripper
    
    # May need tuning for your specific setup
    low_pass_alpha: 0.4
    
  control:
    type: pinocchio
    
    robot_name: kinova_gen3_robotiq_right
    
    robot_config_path: kinova3_2f_85_right.yml
    
    low_pass_alpha: 0.05
    
    disable_orientation_control: False
    
    motion_scaling_factor: 0.8