left:
  retargeting:
    type: vector

    # Path to wxai_base gripper hands
    urdf_path: hands/wxai_base_gripper/wxai_base_gripper.urdf

    wrist_link_name: "link_6"

    target_joint_names: [ "left_carriage_joint" ]

    target_origin_link_names: [ "gripper_right" ]
    target_task_link_names: [ "gripper_left" ]

    scaling_factor: 1.5

    target_link_human_indices: [[4],[8]]

    low_pass_alpha: 0.4

  control:
    type: pinocchio
    robot_name: wxai_base_left

    robot_config_path: wxai_base_left.yml
    low_pass_alpha: 0.05

    disable_orientation_control: False
    motion_scaling_factor: 0.8


right:
  retargeting:
    type: vector

    # Path to wxai_base gripper hands
    urdf_path: hands/wxai_base_gripper/wxai_base_gripper.urdf

    wrist_link_name: "link_6"

    target_joint_names: [ "left_carriage_joint" ]

    target_origin_link_names: [ "gripper_right" ]
    target_task_link_names: [ "gripper_left" ]

    scaling_factor: 1.5

    target_link_human_indices: [[4],[8]]

    low_pass_alpha: 0.4

  control:
    type: pinocchio
    robot_name: wxai_base_right

    robot_config_path: wxai_base_right.yml
    low_pass_alpha: 0.05

    disable_orientation_control: False
    motion_scaling_factor: 0.8